# Ici, se trouve le pipeline de notre projet Todo
# Nous a défini dans ce fichier toutes les étapes de la configuration de notre projet

name: Todo Project's Pipeline


#
on:
  push:
    branches: [ "main", "dev" ] 
  pull_request:
    branches: [ "main", "prod" ] 


#
jobs:
  build:

    #
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

        
    - name: Tests
      if : ${{ github.ref == 'ref/heads/main' }} ||  ${{ github.ref == 'ref/heads/dev' }} 
      run: mvn test

    - name: SonarQube Quality Gate Check
    # You may pin to the exact commit or the version.
    # uses: SonarSource/sonarqube-quality-gate-action@d304d050d930b02a896b0f85935344f023928496
      uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    

    - name: Check Quality Gate
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


    - name: Package
      run: mvn -B package -DskipTests=true #with maven, we pass arg with -D flag and profile with -P flag

    # 
    - name: Dockerize
      run: |
       docker login -u=${{secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}
       docker build -t ${{secrets.DOCKER_REGISTRY_IMAGE }}:${{ github.sha }} -t  ${{secrets.DOCKER_REGISTRY_IMAGE }}:latest . 
       docker push ${{secrets.DOCKER_REGISTRY_IMAGE }} # push all tags

       
    - name: Deploy
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.WEB_SERVER_IP }}
        username: ${{ secrets.WEB_SERVER_USERNAME }}
        key: ${{ secrets.WEB_SERVER_KEY }}
        port: 22
        script: | #script to execute once inside the remote computer
          mkdir -p ~/.ssh
          touch  ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.WEB_SERVER_IP }} >> ~/.ssh/known_hosts
          sudo sudo apt-get update
          sudo apt install docker.io
          docker --version 
          sudo docker container ls -aq --filter name=cicdeptgitdic1 |xargs --no-run-if-empty sudo docker stop |xargs --no-run-if-empty sudo  docker container rm 
          sudo docker run --name cicdeptgitdic1  -d -p 80:8080 marieme27/todos-project-final:latest
   
   
    - name: Wait for deploy to finish
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
        

    - name : Test deploy
      id: tes-deploy-dev
      uses: indiesdev/curl@v1.1
      with:
          url: http://${{ secrets.WEB_SERVER_IP }}/cicd/_health
          method: "GET"
          accept: 200
          timeout: 5000
          log-response: true
          retries: 2
